### ISSUE TITLE
Error: Sizes of tensors must match except in dimension 1. Expected size 26 but got size 25 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by frankyifei** [blepping/comfyui_jankhidiffusion#2]
Change setting in RAUnet seems to change the number of expected size and got size. This only happens in percent mode. Time step mode seems no error but it is also not doing anything with output.
Alright, I found it is only working with certain resolution like for SD1.5, it should be 1024x1024, 2048x2048. Otherwise it will give this error.

**Comment by MythicalChu** [comment]
Same for me after the update, but all time modes lead to the error when trying to upscale

**Comment by blepping** [comment]
@frankyifei @MythicalChu can you share some more information about the settings you're using? the image dimensions and ideally a picture of the `ApplyRAUNet` node.

it does only work for certain resolutions (i believe this is also the case with the official implementation). however you aren't limited to only square resolutions. for example, 2048x1792, 2048x1536, 1024x1536, 1024x1792, 1024x512 work. it may just need to be a multiple of 256, not sure.

the problem likely isn't related to time modes. also note that the `time_mode` setting doesn't change the behavior of the node, it determines how you're supposed to enter the time values. so if you set time mode to timestep then you'd use 999 to mean the start of sampling, 0 to mean the end. if you left it at something like 0 and 0.3 with timestep mode enabled you're saying only activate after sampling is done so nothing will happen.

**Comment by Omarsmsm** [comment]
Anybody got block numbers for SDXL  MSWMSA Attention & ApplyRAU nodes that does a good job?

**Comment by blepping** [comment]
@Omarsmsm 

> Anybody got block numbers for SDXL MSWMSA Attention & ApplyRAU nodes that does a good job?

please create a separate issue if you want to talk about something unrelated to the original issue here. the blocks i suggested using in the README are basically what i found to work best. you can possibly also try input 6, output 2 for the RAUNet blocks.

in general, the results with SDXL didn't seem amazing. the attention patch doesn't seem like a noticeable performance boost but it possibly will help quality at high res. you can also experiment with the possible input/output blocks i mentioned in the README although it's fairly unlikely you'll find something better than what i tested.

**Comment by MythicalChu** [comment]
I didn't realize it needed some specific dimensions, started having errors when I tried to upscale 512x768 by 1.25x , or gen at 384x512.

**Comment by frankyifei** [comment]
I could not get it to work with SDXL at all. I works on some resolution of SD 1.5 like you said. It will gives this mismatch error with SDXL.

**Comment by frankyifei** [comment]
From the diffusers code, I think at least their ratios are depend on resolution. see here: https://github.com/megvii-research/HiDiffusion/blob/dffb528a63de67c89112467c5170b7ffc5e79e45/hidiffusion/hidiffusion.py#L85, maybe it is easier to just offer several options for normal user like me. put all the advanced functions in a separate advanced node like many extensions do.

**Comment by blepping** [comment]
> From the diffusers code, I think at least their ratios are depend on resolution.

right. basically just use end time 0.4 for less extreme resolutions and leave the CA part disabled. for more extreme resolutions they use end_time 0.7, ca_end_time 0.3. that isn't really the complicated part, what i was talking about is selecting the blocks to apply the effect to.

**Comment by blepping** [comment]
@MythicalChu 

>  started having errors when I tried to upscale 512x768 by 1.25x

actually, i don't fully understand this. you can't set the upscale amount so i don't know what "upscale by 1.25x" means. if you mean you just multiplied the initial latent sizes to use 640x960 then that should actually work fine - both those dimensions are divisible by 16 and i just confirmed there is no issue.

i was looking more closely at the code and i think that:

1. the size restriction is just for MSW-MSA attention. can you confirm that is where the error is coming from?
2. the restriction is just that it needs to be divisible by 16 (at least for SD 1.5 with the default blocks in the MSW-MSA attention node)

**Comment by MythicalChu** [comment]
I'm sorry, I worded it badly. I meant it as a 2nd pass, "hires fix", upscaling the latent. The MSW-MSA Node is the one working very flexibly, I've tried many different starting dimensions with 2nd passes of 1.25x, 1.5x and 2.0x, I only had a problem with it in the custom Adetailer part of my workflow, because it sometimes inference on images like 384x384 or smaller. I've stopped using the RAU node entirely (I had misunderstood it's use, but since your recent clarifications I realized I don't need it)

I've used the MSW-MSA since you posted it as a lone .py, and deleted it and installed this repo when it became available. Thank you for the effort!

(unrelated) I've noticed MSW-MSA + Hyper tile combine well and gives a dramatic speed boost on higher resolution gens

**Comment by blepping** [comment]
@MythicalChu 

> I'm sorry, I worded it badly. I meant it as a 2nd pass, "hires fix", upscaling the latent. 

ah, no problem. i can see it breaking with stuff like detailers or tiling. like you already figured out, you don't need it for img2img type stuff anyway (RAUNet/deep shrink type effects that is).

>  Thank you for the effort!

no problem, glad it's useful!

> (unrelated) I've noticed MSW-MSA + Hyper tile combine well and gives a dramatic speed boost on higher resolution gens

:+1: i guess you can only really use that combo for img2img.

**Comment by frankyifei** [comment]
@blepping I get comfyui to print out the SDXL block names in a file. Quite different from diffusers. Have a look. 
[sdxl.blocks_name.txt](https://github.com/blepping/comfyui_jankhidiffusion/files/15208382/sdxl.blocks_name.txt)

**Comment by frankyifei** [comment]
I think for sdxl I am using input block 4,5,6 and output block 3,4,5 for now and it gives good result

**Comment by blepping** [comment]
@frankyifei 

> Quite different from diffusers. Have a look.

thanks - that's basically my issue though, i am not 100% sure how to convert between ComfyUI's conception of where/what blocks are and Diffusers.

i added simple versions of both nodes and made the resolution mismatch error for attention more friendly. hopefully that will make things easier from a user perspective.
