### ISSUE TITLE
ControlNet not working

### ISSUE THREAD

**Issue by DoomedSouls** [blepping/comfyui_jankhidiffusion#5]
According to official [GitHub](https://github.com/megvii-research/HiDiffusion) page, this function should work.

**Comment by blepping** [comment]
>  this function should work.

i'm sure it does in their implementation. this comfyui version doesn't necessarily support all the same features. unfortunately, right now controlnet and RAUNet effects can't overlap (at least for the blocks that are scaled).

i'd like to get it working better with controlnet but i'm not sure when i'll have the time to look at it more in depth. it also may be beyond my capabilities.

we can leave this open as a feature request.

**Comment by blepping** [comment]
i've added an experimental workaround for ControlNet when RAUNet is active. please see https://github.com/blepping/comfyui_jankhidiffusion#use-with-controlnet and let me know if it seems like an improvement!

when it's working, you'll see messages like:

```plaintext
* jankhidiffusion: Scaling controlnet conditioning: torch.Size([24, 24]) -> torch.Size([6, 6])
```

in your log, compared to the normal:

```plaintext
warning control could not be applied torch.Size([2, 1280, 6, 6]) torch.Size([2, 1280, 24, 24])
```

if you need to disable the workaround for some reason, set the environmental variable `JANKHIDIFFUSION_NO_CONTROLNET_WORKAROUND` to anything when running ComfyUI.

**Comment by whmc76** [comment]
> i've added an experimental workaround for ControlNet when RAUNet is active. please see https://github.com/blepping/comfyui_jankhidiffusion#use-with-controlnet and let me know if it seems like an improvement!
> 
> when it's working, you'll see messages like:
> 
> ```
> * jankhidiffusion: Scaling controlnet conditioning: torch.Size([24, 24]) -> torch.Size([6, 6])
> ```
> 
> in your log, compared to the normal:
> 
> ```
> warning control could not be applied torch.Size([2, 1280, 6, 6]) torch.Size([2, 1280, 24, 24])
> ```
> 
> if you need to disable the workaround for some reason, set the environmental variable `JANKHIDIFFUSION_NO_CONTROLNET_WORKAROUND` to anything when running ComfyUI.

god! Yesterday I encountered a problem with controlnet incompatibility. After seeing the information you discussed, I thought this would probably not happen. I didn't expect you to do it.

**Comment by blepping** [comment]
> After seeing the information you discussed, I thought this would probably not happen. I didn't expect you to do it.

i had the idea for this for a while but i didn't know if it would even work. honestly wasn't too enthusiastic about it because i don't think it's the correct fix even if it's an improvement. it also requires patching more of ComfyUI's internals (and even other custom nodes) to work which means there are going to be issues if anything changes in those areas.

did the workaround help for your use case?

**Comment by blepping** [comment]
kind of weird that after so many people asked about ControlNet there was no feedback when i tried to improve the situation so i guess i'll just close this. if it works good, if not ehhh. probably won't be revisiting this issue.
