### ISSUE TITLE
No longer working 😭

### ISSUE THREAD

**Issue by DoomedSouls** [blepping/comfyui_jankhidiffusion#8]
It's not working anymore. Everything is distorted. I'm using ComfyUI 2169 [0fecfd]

**Comment by blepping** [comment]
i'm using the latest versions of both with no issues currently. i can't really help you when the only information i have is "it's broken" - it isn't.

what changed between when it worked for you and when it didn't? did you update comfyui? did you update jankhidiffusion? are you testing with the _exact_ workflow that was fine before, or possibly something else changed in it that could cause issues?
