### ISSUE TITLE
Error:Cannot import /ComfyUI/custom_nodes/comfyui_jankhidiffusion module for custom nodes: invalid syntax (msw_msa_attention.py, line 92)

### ISSUE THREAD

**Issue by Ceciliammm** [blepping/comfyui_jankhidiffusion#9]
os:linux

## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-10 03:43:36.985964
** Platform: Linux
** Python version: 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
[GCC 12.3.0]
** Python executable: /opt/conda/envs/comfyui/bin/python
** Log path: /home/ubuntu/MHF/AIGC/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.1 seconds: /home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 22516 MB, total RAM 63609 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A10G : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 2169 [0fecfd2b] | Released on '2024-05-09'
Traceback (most recent call last):
  File "/home/ubuntu/MHF/AIGC/ComfyUI/nodes.py", line 1867, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/comfyui_jankhidiffusion/__init__.py", line 1, in <module>
    from .py import *
  File "/home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/comfyui_jankhidiffusion/py/__init__.py", line 1, in <module>
    from .msw_msa_attention import *
  File "/home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/comfyui_jankhidiffusion/py/msw_msa_attention.py", line 92
    match shift:
          ^
SyntaxError: invalid syntax

Cannot import /home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/comfyui_jankhidiffusion module for custom nodes: invalid syntax (msw_msa_attention.py, line 92)

Import times for custom nodes:
   0.0 seconds: /home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/comfyui_jankhidiffusion
   0.1 seconds: /home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: /home/ubuntu/MHF/AIGC/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json

**Comment by blepping** [comment]
`match`/`case` were added in Python 3.10 while you have 3.9. i refactored some stuff to use plain if statements (hopefully without breaking anything else). try updating. not sure if there are other things that Python 3.9 can't handle but that specific issue should be fixed now at least.

**Comment by Ceciliammm** [comment]
作业已收到。

**Comment by blepping** [comment]
现在还有问题没有？

**Comment by Ceciliammm** [comment]
> 现在还有问题没有？

没有问题了，非常感谢！！！！！！！

**Comment by blepping** [comment]
不客气啊！
